const express = require('express');
const { protectRoute} = require("../auth/protect");
const { loginView,loginUser,registerView,registerUser,catalogView } = require('../controllers/loginController');
const { homeView ,welcomeView,transitionView,seatView,game,waitView,deliverView,processingView} = require('../controllers/homeController');
const { Upload,ContactsView,ContactsCRUD,ContactsData} = require('../controllers/contactsController');
const { InventoryView, InventoryUpload } = require('../controllers/inventoryController');
const { menuView,getflavor,UploadOrder,OrderList,orderDel,orderDetail, getInventoryArray,OrderSearch} = require('../controllers/menuController');
const {UploadReserve,ReserveSearch}=require('../controllers/reservationController');
const {mazeView,handView,pricechange}=require('../controllers/gameController');
const request=require('request-promise');
const router = express.Router();
router.get('/', welcomeView);
router.get('/home',homeView);
router.get('/login', loginView);
router.post('/login',loginUser);
router.post('/comment',Upload);
router.get('/Contacts',protectRoute,ContactsView);
router.post('/Contacts',ContactsCRUD);
router.post('/ContactsData',ContactsData);
router.get('/inventory',protectRoute,InventoryView);
router.post('/inventory',InventoryUpload);
router.get("/register",protectRoute, registerView);
router.post("/register", registerUser);
router.get("/catalog",protectRoute,catalogView);
router.get ("/menu",menuView);
router.get ("/menuDetail",protectRoute,OrderList);
router.post("/orderDel",orderDel);
router.post("/orderDetail",orderDetail);
router.post("/orderSearch",OrderSearch);
router.post ("/menu",UploadOrder);
router.post ("/flavor",getflavor);
router.post("/reserve",UploadReserve);
router.post("/reservecheck",ReserveSearch);
router.get('/transition',transitionView);
router.get('/wait',waitView);
router.get('/logout', function (req, res){
    req.session.destroy(function (err) {
      res.redirect('/login'); 
    });
});
router.get('/processing',processingView);
router.get('/seat',protectRoute,seatView);
router.post('/food',getInventoryArray);
router.get('/maze',mazeView);
router.get('/handGame',handView);
router.get('/deliver',deliverView);
router.post('/discount',pricechange);
module.exports = router;